/**
 * Booking serviceType (API enum) → ServiceCatalog.name.
 * Shared by bookingService (pricing) and careSuppliesService (supplies).
 */
const SERVICE_TYPE_TO_CATALOG_NAME = Object.freeze({
  INJECTION: 'INJECTION_IM',
  IV_DRIP: 'IV_DRIP',
  WOUND_DRESSING: 'WOUND_DRESSING',
  CATHETER_CARE: 'CATHETER_CARE',
  POST_SURGERY_CARE: 'POST_SURGERY_CARE',
  ELDERLY_CARE: 'ELDERLY_CARE_DAILY',
  PHYSIOTHERAPY_SESSION: 'PHYSIO_SESSION',
  BACK_PAIN_THERAPY: 'BACK_PAIN_PHYSIO',
  KNEE_PAIN_THERAPY: 'KNEE_PAIN_PHYSIO',
  POST_SURGERY_REHAB: 'POST_SURGERY_REHAB',
  STROKE_REHAB: 'STROKE_REHAB',
  PHYSIO_PACKAGE_10: 'PHYSIO_PACKAGE_10',
  ELDERLY_CARE_PACKAGE: 'ELDERLY_CARE_MONTHLY',
  POST_SURGERY_PACKAGE: 'POST_SURGERY_14DAY'
});

const CATALOG_NAME_TO_SERVICE_TYPE = Object.freeze(
  Object.fromEntries(Object.entries(SERVICE_TYPE_TO_CATALOG_NAME).map(([type, name]) => [name, type]))
);

module.exports = { SERVICE_TYPE_TO_CATALOG_NAME, CATALOG_NAME_TO_SERVICE_TYPE };
