const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..', '..', '..');

const readProjectFile = (relativePath) => fs.readFileSync(path.join(rootDir, relativePath), 'utf8');

const frontendSessionSrc = readProjectFile('client/public/js/frontend-session.js');
const landingSrc = readProjectFile('client/public/js/landing.js');
const sharedRegisterSrc = readProjectFile('client/public/shared/register.html');
const sharedRegisterScriptSrc = readProjectFile('client/public/js/shared-register.js');
const patientLoginSrc = readProjectFile('client/public/roles/patient/patient-login.html');
const providerLoginSrc = readProjectFile('client/public/roles/provider/provider-login.html');
const patientRegisterSrc = readProjectFile('client/public/roles/patient/patient-register.html');
const patientLoginScriptSrc = readProjectFile('client/public/js/patient-login.js');
const providerLoginScriptSrc = readProjectFile('client/public/js/provider-login.js');
const patientRegisterScriptSrc = readProjectFile('client/public/js/patient-register.js');
const doctorOnboardingSrc = readProjectFile('client/public/roles/doctor/doctor-onboarding.html');
const doctorOnboardingScriptSrc = readProjectFile('client/public/js/doctor-onboarding.js');
const providerSessionSrc = readProjectFile('client/public/js/provider-session.js');

describe('Frontend Auth Flow Standardization', () => {
  it('should centralize auth form error mapping and message rendering in frontend-session.js', () => {
    expect(frontendSessionSrc).toContain('function renderFormMessage(container, message, options)');
    expect(frontendSessionSrc).toContain('function renderSuccessMessage(container, message, options)');
    expect(frontendSessionSrc).toContain('function clearFormMessage(container)');
    expect(frontendSessionSrc).toContain('function setButtonLoading(button, options)');
    expect(frontendSessionSrc).toContain('function resetButtonState(button, options)');
    expect(frontendSessionSrc).toContain('function getLoginErrorMessage(error, overrides)');
    expect(frontendSessionSrc).toContain('function getRegistrationErrorMessage(error, overrides)');
    expect(frontendSessionSrc).toContain('function expectJsonSuccess(data, fallbackMessage, options)');
    expect(frontendSessionSrc).toContain('function completeAuthSuccess(authData, options)');
    expect(frontendSessionSrc).toContain('function validateRequiredValue(value, container, message, options)');
    expect(frontendSessionSrc).toContain('function validatePasswordMatch(password, confirmPassword, container, options)');
    expect(frontendSessionSrc).toContain('function validatePhoneNumber(phone, container, options)');
    expect(frontendSessionSrc).toContain('function getPasswordStrengthState(password)');
    expect(frontendSessionSrc).toContain('function validatePasswordStrength(password, container, options)');
    expect(frontendSessionSrc).toContain('function handleValidationFailure(container, message, config)');
    expect(frontendSessionSrc).toContain('button.dataset.originalHtml');
    expect(frontendSessionSrc).toContain('if (config.loadingHtml)');
    expect(frontendSessionSrc).toContain('if (config.htmlContent)');
    expect(frontendSessionSrc).toContain("if (typeof config.onInvalid === 'function')");
    expect(frontendSessionSrc).toContain('isSuccess: function (payload) {');
    expect(frontendSessionSrc).toContain("invalidCredentialsMessage: 'Invalid email or password. Please try again.'");
    expect(frontendSessionSrc).toContain("defaultMessage: 'Registration failed. Please try again.'");
    expect(frontendSessionSrc).toContain("message: 'Password must be at least 8 characters with uppercase, lowercase, number, and special character.'");
  });

  it('should route shared login and register page error handling through the session helper', () => {
    expect(landingSrc).toContain('NocturnalSession.getLoginErrorMessage(error)');
    expect(landingSrc).toContain('NocturnalSession.getRegistrationErrorMessage(error');
    expect(landingSrc).toContain('NocturnalSession.clearFormMessage(errorDiv)');
    expect(landingSrc).toContain('NocturnalSession.validatePasswordStrength(password, errorDiv)');
    expect(landingSrc).toContain('NocturnalSession.validatePasswordMatch(password, confirmPassword, errorDiv');
    expect(landingSrc).toContain('NocturnalSession.setButtonLoading(btn)');
    expect(landingSrc).toContain('NocturnalSession.resetButtonState(btn)');
    expect(landingSrc).toContain('NocturnalSession.expectJsonSuccess(data, \'Login failed\'');
    expect(landingSrc).toContain('NocturnalSession.expectJsonSuccess(data, \'Registration failed\'');
    expect(landingSrc).toContain('NocturnalSession.completeAuthSuccess(');
    expect(landingSrc).toContain('useRoleRedirect: true');

    expect(sharedRegisterSrc).toContain('<script src="/js/frontend-session.js"></script>');
    expect(sharedRegisterSrc).toContain('<script src="/js/shared-register.js"></script>');
    expect(sharedRegisterScriptSrc).toContain('NocturnalSession.getRegistrationErrorMessage(error');
    expect(sharedRegisterScriptSrc).toContain('NocturnalSession.clearFormMessage(errorDiv)');
    expect(sharedRegisterScriptSrc).toContain('NocturnalSession.getPasswordStrengthState(password)');
    expect(sharedRegisterScriptSrc).toContain('NocturnalSession.validatePasswordStrength(password, errorDiv)');
    expect(sharedRegisterScriptSrc).toContain('NocturnalSession.validateRequiredValue(');
    expect(sharedRegisterScriptSrc).toContain('NocturnalSession.validatePasswordMatch(password, confirmPassword, errorDiv');
    expect(sharedRegisterScriptSrc).toContain('NocturnalSession.setButtonLoading(btn)');
    expect(sharedRegisterScriptSrc).toContain('NocturnalSession.resetButtonState(btn)');
    expect(sharedRegisterScriptSrc).toContain('NocturnalSession.expectJsonSuccess(data, \'Registration failed\'');
    expect(sharedRegisterScriptSrc).toContain('NocturnalSession.completeAuthSuccess(');
    expect(sharedRegisterScriptSrc).toContain('skipAuth: true');
    expect(sharedRegisterScriptSrc).toContain('parseJson: true');
    expect(sharedRegisterScriptSrc).toContain('useRoleRedirect: true');

    expect(patientLoginSrc).toContain('<script src="/js/frontend-session.js"></script>');
    expect(patientLoginSrc).toContain('<script src="/js/patient-login.js"></script>');
    expect(patientLoginScriptSrc).toContain('NocturnalSession.clearFormMessage(errorDiv)');
    expect(patientLoginScriptSrc).toContain('NocturnalSession.getLoginErrorMessage(error');
    expect(patientLoginScriptSrc).toContain("NocturnalSession.setButtonLoading(btn, { clearText: true })");
    expect(patientLoginScriptSrc).toContain("NocturnalSession.resetButtonState(btn, { textContent: 'Login' })");
    expect(patientLoginScriptSrc).toContain('NocturnalSession.expectJsonSuccess(data, \'Login failed\'');
    expect(patientLoginScriptSrc).toContain('NocturnalSession.completeAuthSuccess(');
    expect(patientLoginScriptSrc).toContain('skipAuth: true');
    expect(patientLoginScriptSrc).toContain('parseJson: true');
    expect(patientLoginSrc).not.toContain("tokenKey: 'patientToken'");

    expect(providerLoginSrc).toContain('<script src="/js/frontend-session.js"></script>');
    expect(providerLoginSrc).toContain('<script src="/js/provider-session.js"></script>');
    expect(providerLoginSrc).toContain('<script src="/js/provider-login.js"></script>');
    expect(providerLoginSrc).not.toContain('onclick="installPWA()"');
    expect(providerLoginScriptSrc).toContain('ProviderSession.redirectAuthenticatedLogin({');
    expect(providerLoginScriptSrc).toContain('NocturnalSession.clearFormMessage(messageDiv)');
    expect(providerLoginScriptSrc).toContain('NocturnalSession.getLoginErrorMessage(error');
    expect(providerLoginScriptSrc).toContain("{ className: 'message error' }");
    expect(providerLoginScriptSrc).toContain("NocturnalSession.setButtonLoading(btn, { clearText: true })");
    expect(providerLoginScriptSrc).toContain("NocturnalSession.resetButtonState(btn, { textContent: 'Login' })");
    expect(providerLoginScriptSrc).toContain('NocturnalSession.expectJsonSuccess(data, \'Login failed\'');
    expect(providerLoginScriptSrc).toContain('NocturnalSession.completeAuthSuccess(authData, {');
    expect(providerLoginScriptSrc).toContain('skipAuth: true');
    expect(providerLoginScriptSrc).toContain('parseJson: true');
    expect(providerLoginScriptSrc).toContain("successClassName: 'message success'");
    expect(providerLoginScriptSrc).toContain("installPwaButton.addEventListener('click', installPWA);");
    expect(providerLoginSrc).not.toContain("tokenKey: 'providerToken'");
    expect(providerSessionSrc).toContain('NocturnalSession.createRoleSession({');
    expect(providerSessionSrc).toContain("role: 'provider'");
    expect(providerSessionSrc).toContain("legacyTokenKeys: ['providerToken']");
    expect(providerSessionSrc).toContain('session.redirectAuthenticatedLogin = function(options)');

    expect(patientRegisterSrc).toContain('<script src="/js/frontend-session.js"></script>');
    expect(patientRegisterSrc).toContain('<script src="/js/patient-register.js"></script>');
    expect(patientRegisterScriptSrc).toContain('NocturnalSession.clearFormMessage(errorDiv)');
    expect(patientRegisterScriptSrc).toContain('NocturnalSession.getRegistrationErrorMessage(error');
    expect(patientRegisterScriptSrc).toContain('NocturnalSession.validatePasswordStrength(password, errorDiv)');
    expect(patientRegisterScriptSrc).toContain('NocturnalSession.validatePasswordMatch(password, confirmPassword, errorDiv');
    expect(patientRegisterScriptSrc).toContain('NocturnalSession.validatePhoneNumber(phone, errorDiv');
    expect(patientRegisterSrc).toContain('uppercase, lowercase, number & special character');
    expect(patientRegisterScriptSrc).toContain("NocturnalSession.setButtonLoading(btn, { clearText: true })");
    expect(patientRegisterScriptSrc).toContain("NocturnalSession.resetButtonState(btn, { textContent: 'Create Account' })");
    expect(patientRegisterScriptSrc).toContain('NocturnalSession.expectJsonSuccess(data, \'Registration failed\'');
    expect(patientRegisterScriptSrc).toContain('NocturnalSession.completeAuthSuccess(');
    expect(patientRegisterScriptSrc).toContain('skipAuth: true');
    expect(patientRegisterScriptSrc).toContain('parseJson: true');
    expect(patientRegisterScriptSrc).toContain("redirectUrl: AppConfig.routes.page('patient.dashboard')");
    expect(patientRegisterSrc).not.toContain("tokenKey: 'patientToken'");

    expect(doctorOnboardingSrc).toContain('<script src="/js/frontend-session.js"></script>');
    expect(doctorOnboardingSrc).toContain('<script type="module" src="/js/doctor-onboarding.js"></script>');
    expect(doctorOnboardingScriptSrc).toContain('NocturnalSession.validatePasswordStrength(password, null, {');
    expect(doctorOnboardingScriptSrc).toContain('NocturnalSession.validatePasswordMatch(password, confirmPassword, null, {');
    expect(doctorOnboardingScriptSrc).toContain("onInvalid: (message) => showAlert(message, 'danger')");
    expect(doctorOnboardingScriptSrc).toContain("NocturnalSession.setButtonLoading(submitBtn, {");
    expect(doctorOnboardingScriptSrc).toContain("loadingHtml: '<i class=\"fas fa-spinner fa-spin\"></i> Processing...'");
    expect(doctorOnboardingScriptSrc).toContain('NocturnalSession.resetButtonState(submitBtn)');
    expect(doctorOnboardingScriptSrc).toContain("const data = await AppConfig.fetchRoute('auth.register', {");
    expect(doctorOnboardingScriptSrc).toContain('NocturnalSession.expectJsonSuccess(data, \'Registration failed\'');
    expect(doctorOnboardingScriptSrc).toContain('skipAuth: true');
    expect(doctorOnboardingScriptSrc).toContain('parseJson: true');
    expect(doctorOnboardingScriptSrc).toContain("const data = await AppConfig.fetchRoute('auth.me', {");
    expect(doctorOnboardingScriptSrc).toContain('NocturnalSession.expectJsonSuccess(data, \'Failed to update profile\'');
    expect(doctorOnboardingScriptSrc).toContain("NocturnalSession.persistSession(authData.user, 'doctor')");
    expect(doctorOnboardingScriptSrc).toContain("result = await AppConfig.fetchRoute('uploads.profilePhoto', requestOptions);");
    expect(doctorOnboardingScriptSrc).toContain("result = await AppConfig.fetchRoute('uploads.document', requestOptions, {");
    expect(doctorOnboardingScriptSrc).toContain('NocturnalSession.expectJsonSuccess(result, `Failed to upload ${type}: Upload failed`)');
    expect(doctorOnboardingScriptSrc).not.toContain('password.length < 6');
    expect(doctorOnboardingScriptSrc).not.toContain('${API_URL}${endpoint}');
  });
});
